"""Temporary name translation for the immutable legacy HDF5 contract.

The application and FPGA interface use the firmware v1 names exclusively.
Only the HDF5 writer should use these mappings.  Pass ``None`` instead of the
mapping to opt out once downstream readers no longer require legacy metadata
attribute names; this module can then be removed in a future major version.
"""

from __future__ import annotations

from collections.abc import Mapping
from typing import Any


# Optional compatibility mapping: new runtime register name -> legacy HDF5 name.
# Do not use this dictionary for hardware access or internal application state.
LEGACY_H5_REGISTER_NAME_MAP: dict[str, str] = {
    "analog_a_channel_0_integrate_enable": "AnalogA0 integrate",
    "analog_a_channel_0_invert_enable": "AnalogA0 invert",
    "analog_a_channel_1_integrate_enable": "AnalogA1 integrate",
    "analog_a_channel_1_invert_enable": "AnalogA1 invert",
    "analog_a_channel_2_integrate_enable": "AnalogA2 integrate",
    "analog_a_channel_2_invert_enable": "AnalogA2 invert",
    "analog_a_channel_3_integrate_enable": "AnalogA3 integrate",
    "analog_a_channel_3_invert_enable": "AnalogA3 invert",
    "analog_a_channel_4_integrate_enable": "AnalogA4 integrate",
    "analog_a_channel_4_invert_enable": "AnalogA4 invert",
    "analog_a_channel_5_integrate_enable": "AnalogA5 integrate",
    "analog_a_channel_5_invert_enable": "AnalogA5 invert",
    "analog_a_channel_6_integrate_enable": "AnalogA6 integrate",
    "analog_a_channel_6_invert_enable": "AnalogA6 invert",
    "analog_a_channel_7_integrate_enable": "AnalogA7 integrate",
    "analog_a_channel_7_invert_enable": "AnalogA7 invert",
    "analog_a_differential_mode_enable": "AnalogA differential",
    "analog_a_input_selector": "AnalogInputA",
    "analog_b_differential_mode_enable": "AnalogB differential",
    "analog_b_input_selector": "AnalogInputB",
    "analog_input_0_volts": "AnalogIN0",
    "analog_input_1_volts": "AnalogIN1",
    "analog_input_2_volts": "AnalogIN2",
    "analog_input_3_volts": "AnalogIN3",
    "analog_input_4_volts": "AnalogIN4",
    "analog_input_5_volts": "AnalogIN5",
    "analog_input_6_volts": "AnalogIN6",
    "analog_input_7_volts": "AnalogIN7",
    "analog_output_0_dc_volts": "AnalogOutDC_0",
    "analog_output_0_source_selector": "AnalogSelector_0",
    "analog_output_0_volts": "AnalogOUT0",
    "analog_output_1_dc_volts": "AnalogOutDC_1",
    "analog_output_1_source_selector": "AnalogSelector_1",
    "analog_output_1_volts": "AnalogOUT1",
    "analog_output_2_dc_volts": "AnalogOutDC_2",
    "analog_output_2_source_selector": "AnalogSelector_2",
    "analog_output_2_volts": "AnalogOUT2",
    "analog_output_3_dc_volts": "AnalogOutDC_3",
    "analog_output_3_source_selector": "AnalogSelector_3",
    "analog_output_3_volts": "AnalogOUT3",
    "analog_output_4_dc_volts": "AnalogOutDC_4",
    "analog_output_4_source_selector": "AnalogSelector_4",
    "analog_output_4_volts": "AnalogOUT4",
    "analog_output_5_dc_volts": "AnalogOutDC_5",
    "analog_output_5_source_selector": "AnalogSelector_5",
    "analog_output_5_volts": "AnalogOUT5",
    "analog_output_6_dc_volts": "AnalogOutDC_6",
    "analog_output_6_source_selector": "AnalogSelector_6",
    "analog_output_6_volts": "AnalogOUT6",
    "analog_output_7_dc_volts": "AnalogOutDC_7",
    "analog_output_7_source_selector": "AnalogSelector_7",
    "analog_output_7_volts": "AnalogOUT7",
    "axis_calibration_volts_per_step": "CalibrationFactors(V/step)",
    "axis_start_offset_volts": "Offset/StartValue (V)",
    "circular_scan_enable": "CircularMotionActivate",
    "circular_scan_x_volts": "ScanXVoltages",
    "circular_scan_y_volts": "ScanYVoltages",
    "circular_scan_z_volts": "ScanZVoltages",
    "current_circular_point_index": "cur_circ_point",
    "current_circular_repetition_index": "cur_circ_rep",
    "current_cycle_index": "cur_cycle",
    "current_laser_time_bin_index": "LaserNumberTimeBinCurrent",
    "current_line_parity_flag": "cur_parity",
    "current_repetition_index": "cur_rep",
    "current_time_bin_index": "cur_t",
    "current_x_index": "cur_x",
    "current_y_index": "cur_y",
    "current_z_index": "cur_z",
    "custom_positions_current_address": "CustomPos_position_curr_addr",
    "custom_positions_enable": "UseCustomPositions",
    "custom_positions_extra_flag": "CustomPos_position_extra",
    "custom_positions_last_framewise_address": "CustomPos_LastAddrFramewise",
    "custom_positions_last_pixelwise_address": "CustomPos_LastAddrPixelwise",
    "custom_positions_offset_current_address": "CustomPos_offset_curr_addr",
    "custom_positions_offset_extra_flag": "CustomPos_offset_extra",
    "custom_positions_offset_tx_begin_flag": "CustomPos_offset_begin_tx",
    "custom_positions_offset_tx_end_flag": "CustomPos_offset_end_tx",
    "custom_positions_offset_update_mode_flag": "CustomPos_offset_pixelwise-framewise",
    "custom_positions_offset_x_volts": "CustomPos_offset_X",
    "custom_positions_offset_y_volts": "CustomPos_offset_Y",
    "custom_positions_offset_z_volts": "CustomPos_offset_Z",
    "custom_positions_stream_in_ready_flag": "CustomPos_FIFOPositionReady",
    "custom_positions_tx_begin_flag": "CustomPos_position_begin_tx",
    "custom_positions_tx_end_flag": "CustomPos_position_end_tx",
    "custom_positions_update_mode_flag": "CustomPos_position_pixelwise-framewise",
    "custom_positions_x_volts": "CustomPos_position_X",
    "custom_positions_y_volts": "CustomPos_position_Y",
    "custom_positions_z_volts": "CustomPos_position_Z",
    "debug_circular_point_index": "circ_point",
    "debug_circular_repetition_index": "circ_rep",
    "debug_circular_repetition_tag": "Circular Repetition tag",
    "debug_end_of_frame_flag": "End of frame",
    "debug_frame_tag": "Frame tag",
    "debug_line_counter": "LC",
    "debug_line_tag": "Line tag",
    "debug_pixel_tag": "Pixel tag",
    "debug_repetition_index": "rrep",
    "debug_repetition_tag": "Repetition tag",
    "debug_scan_fsm_status": "FSM Status",
    "debug_t": "t",
    "debug_x_index": "rx",
    "debug_x_index_2": "rx2",
    "debug_y_index": "ry",
    "debug_y_index_2": "ry2",
    "debug_z_index": "rz",
    "debug_z_index_2": "rz2",
    "detector_49_channel_mode_enable": "49_enable",
    "detector_fpga_holdoff_cycles": "holdOff",
    "dfd_acquisition_active_status": "DFD_FSM_Acquisition",
    "dfd_bin_count": "DFDnBins",
    "dfd_current_position_index": "DFD_px_Current",
    "dfd_dwell_time_cycles_120mhz": "DFD Dwell time (120MHz)",
    "dfd_enable": "DFD_Activate",
    "dfd_internal_dwell_time_enable": "DFD_Uses_Own_Dwelltime",
    "dfd_laser_sync_debug_enable": "DFD_LaserSyncDebug",
    "dfd_transmitted_position_index": "DFD_px_Transmitted",
    "dfd_trigger_selector": "DFD_Trig_Selector",
    "dummy_data_enable": "DummyData",
    "firmware_dfd_fast_to_excitation_frequency_ratio": "ratio freq_fast/freq_exc",
    "firmware_external_clock_active_flag": "Ext_clk",
    "firmware_external_dac_active_flag": "FLAG_ExtDAC",
    "firmware_force_25_channel_mode_active_flag": "FLAG_Force25",
    "firmware_gi_dac_adc_active_flag": "FLAG_GI_DAC_ADC",
    "gi_dac_adc_short_cable_mode_enable": "GI_DAC_ADC_ShortCableMode",
    "internal_fifo_analog_overflow_flag": "FIFOAnalog_Overflow",
    "internal_fifo_dfd_overflow_flag": "DFD_FIFO_Overflow",
    "internal_fifo_spad_overflow_flag": "FIFO_Overflow",
    "laser_1_enable": "LaserEnable0",
    "laser_2_enable": "LaserEnable1",
    "laser_3_enable": "LaserEnable2",
    "laser_4_enable": "LaserEnable3",
    "laser_excitation_sequence": "excitation sequence",
    "laser_force_pulsing_enable": "LaserForcePulsing",
    "laser_off_after_measurement_enable": "LaserOffAfterMeasurement",
    "laser_time_bin_mode_enable": "activateLaserTimeBin",
    "max_circular_point": "#circular_points",
    "max_circular_repetition": "#circular_rep",
    "max_frame": "#frames",
    "max_laser_time_bin": "maxLaserTimeBin",
    "max_line": "#lines",
    "max_pixel": "#pixels",
    "max_repetition": "#repetition",
    "max_time_bins_per_pixel": "#timebinsPerPixel",
    "max_x_volts": "MaxXVoltages",
    "max_y_volts": "MaxYVoltages",
    "max_z_volts": "MaxZVoltages",
    "min_x_volts": "MinXVoltages",
    "min_y_volts": "MinYVoltages",
    "min_z_volts": "MinZVoltages",
    "redirect_intensity_to_stream_out_aux_enable": "Redirect_intensity_to_FIFOAnalog",
    "shutter_enable": "shutters",
    "slave_mode_emulated_pixel_count": "SlaveMode_PxEmulated",
    "slave_mode_enable": "SlaveMode",
    "slave_mode_event_count": "SlaveMode_Count",
    "slave_mode_external_source_selector": "ext_px_selector",
    "slave_mode_max_event_count": "SlaveMode_CountMax",
    "slave_mode_test_generator_enable": "SlaveModeTestGen",
    "spad_configuration_message": "msgOut",
    "spad_configuration_message_length": "msgLen",
    "spad_sdata_invert_enable": "Invert SDATA",
    "spad_vr0_enable": "VR0",
    "spad_vr1_enable": "VR1",
    "start_command": "Run",
    "stop_command": "stop",
    "stream_out_aux_enable": "activateFIFOAnalog",
    "stream_out_aux_overflow_cycle_counter": "FIFO Failed",
    "stream_out_main_enable": "activateFIFODigital",
    "stream_out_main_overflow_cycle_counter": "FIFOAnalog Failed",
    "tag_clock_duration_cycles": "ClockDur",
    "tag_turnoff_frame_counter": "turnOffFC",
    "tag_turnoff_line_counter": "turnOffLC",
    "tag_turnoff_pixel_counter": "turnOffPC",
    "time_bin_dwell_cycles": "Cx",
    "wait_laser_first_time_only_enable": "WaitOnlyFirstTime",
    "wait_laser_startup_cycles": "WaitForLaser",
    "wait_post_frame_cycles": "WaitAfterFrame",
    "wait_initialization_time_in_us": "initializationTime",
    "xy_snake_scan_enable": "snake",
    "z_snake_scan_enable": "snake_z",
}


# Optional compatibility mapping for any HDF5 metadata dictionaries keyed by
# runtime FIFO name. RAW file basenames intentionally remain ``_FIFO.raw`` and
# ``_FIFOAnalog.raw`` as part of the stable on-disk format.
LEGACY_H5_FIFO_NAME_MAP: dict[str, str] = {
    "stream_in": "FIFO In",
    "stream_out_aux": "FIFOAnalog",
    "stream_out_main": "FIFO",
}


def translate_metadata_names(
    values: Mapping[str, Any],
    name_map: Mapping[str, str] | None = None,
) -> dict[str, Any]:
    """Return metadata with optionally translated keys.

    ``None`` disables compatibility translation, making removal of the legacy
    HDF5 naming layer a one-line change at each storage call site.
    """

    if name_map is None:
        return dict(values)
    return {name_map.get(name, name): value for name, value in values.items()}
