"""Structural interfaces used by the application layer."""

from __future__ import annotations

from typing import Any, Protocol, runtime_checkable

import numpy as np


@runtime_checkable
class ProcessHandle(Protocol):
    def start(self) -> None: ...
    def is_alive(self) -> bool: ...
    def join(self, timeout: float | None = None) -> None: ...
    def terminate(self) -> None: ...


@runtime_checkable
class HardwareControl(Protocol):
    def register_read(self, register: str, timeout: int = 1000) -> Any: ...
    def register_write(self, register: str, data: Any) -> None: ...
    def stop(self) -> None: ...


@runtime_checkable
class AcquisitionWriter(Protocol):
    def init_dataset(self, dataset_name: str, shape: Any, timebinsPerPixel: int, channels: int, dtype: Any) -> None: ...
    def add_to_dataset(self, dataset_name: str, buffer_for_save: Any, current_rep: int, current_z: int) -> None: ...
    def close(self) -> None: ...


@runtime_checkable
class PreviewData(Protocol):
    def get_preview_image(self, projection: str = "xy", rgb: bool = False) -> np.ndarray: ...
    def get_fingerprint(self) -> np.ndarray: ...


@runtime_checkable
class DetectorPipeline(Protocol):
    detector_model: str

    def make_receiver_queue(self, acquisition: Any) -> Any: ...
    def make_receiver_process(self, acquisition: Any, receiver_queue: Any, start_event: Any) -> Any: ...
    def make_data_preprocess(self, acquisition: Any, receiver_queue: Any) -> ProcessHandle: ...
    def make_acquisition_loop(self, acquisition: Any, do_not_save: Any) -> ProcessHandle: ...
    def make_raw_stream_writer(self, acquisition: Any, receiver_queue: Any) -> ProcessHandle: ...
